bot:
  name: ${TG_BOT_NAME:botName_bot}
  token: ${TG_BOT_TOKEN:token}
  channelName: channelName
  managerId: managerId
  adminId: adminId
  serverUrl: 192.168.0.100:9090
  loyaltyUrl: ссылка_на_домен
  secure: false