server:
  port: 9093

serviceUrl:
  dataStorage: http://localhost:9092
  oneC: http://localhost:9094
  frontend: http://localhost:9090


spring:
  jackson:
    time-zone: Europe/Moscow
  profiles:
    active: dev
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
      timeout-seconds: 1

logging:
  level:
    ru.telebot: DEBUG
  file:
    name: ./backend/TeleBot/logs/app.log
    path: logs

interval:
  phones: PT4H

propsFile: ./backend/TeleBot/src/main/resources/application-${spring.profiles.active}.yaml