server:
  port: 9093
dataStorage:
  url: http://localhost:9092

spring:
  profiles:
    active: dev
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
      timeout-seconds: 1

logging:
  level:
    ru.telebot: DEBUG
  file:
    name: ./backend/TeleBot/logs/app.log
    path: logs