server:
  port: 9092

spring:
  jackson:
    time-zone: Europe/Moscow
  profiles:
    active: prod
  liquibase:
    change-log: db/changelog/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


logging:
  level:
    ru.telebot: DEBUG
  file:
    name: ./backend/DataStorage/logs/app.log
    path: logs
