server:
  port: 9092

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/iMarket
    username: postgres
    password: 123
  liquibase:
    change-log: db/changelog/changelog.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


logging:
  level:
    ru.telebot: DEBUG
  file:
    name: ./backend/DataStorage/logs/app.log
    path: logs
